#[derive(Debug, Clone)]
pub struct NewProduct {
    pub product_type: String,
    pub schema_name: String,
    pub schema_version: i64,
    pub cell_id: String,
    pub family_id: Option<String>,
    pub content_sha256: String,
    pub storage_kind: String,
    pub storage_ref: String,
    pub created_by_algorithm: String,
    pub algorithm_version: String,
    pub config_sha256: String,
    pub code_sha256: Option<String>,
    pub valid_time_start: Option<String>,
    pub valid_time_end: Option<String>,
    pub source_time: Option<String>,
    pub accepted_at: Option<String>,
    pub ingested_at: Option<String>,
    pub available_at: String,
    pub hazard_class: String,
    pub parent_product_ids: Vec<(String, String)>,
}

#[derive(Debug, Clone)]
pub struct DataProduct {
    pub product_id: String,
    pub product_type: String,
    pub schema_name: String,
    pub schema_version: i64,
    pub cell_id: String,
    pub family_id: Option<String>,
    pub content_sha256: String,
    pub storage_kind: String,
    pub storage_ref: String,
    pub created_by_algorithm: String,
    pub algorithm_version: String,
    pub config_sha256: String,
    pub code_sha256: Option<String>,
    pub valid_time_start: Option<String>,
    pub valid_time_end: Option<String>,
    pub source_time: Option<String>,
    pub accepted_at: Option<String>,
    pub ingested_at: Option<String>,
    pub available_at: String,
    pub created_at: String,
    pub hazard_class: String,
}
